# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Apr  9 13:14:56 2014

import wx
from numpy import *
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
from mpl_toolkits.mplot3d import Axes3D
# begin wxGlade: dependencies
from MplPanel_1 import MplPanel_1
from MplPanel_2 import MplPanel_2
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class Cuadro(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Cuadro.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Mach mínimo", style=wx.ALIGN_CENTRE)
        self.Mmin = wx.TextCtrl(self, -1, "0")
        self.label_4 = wx.StaticText(self, -1, "Altitud mínima [m]", style=wx.ALIGN_CENTRE)
        self.hmin = wx.TextCtrl(self, -1, "0")
        self.label_7 = wx.StaticText(self, -1, "Diámetro del borde de ataque [m]", style=wx.ALIGN_CENTRE)
        self.diam = wx.TextCtrl(self, -1, "0.2")
        self.label_2 = wx.StaticText(self, -1, "Mach máximo", style=wx.ALIGN_CENTRE)
        self.Mmax = wx.TextCtrl(self, -1, "1")
        self.label_5 = wx.StaticText(self, -1, "Altitud máxima [m]", style=wx.ALIGN_CENTRE)
        self.hmax = wx.TextCtrl(self, -1, "11000")
        self.label_8 = wx.StaticText(self, -1, "Altura mojada del perfil [m]", style=wx.ALIGN_CENTRE)
        self.altcorte = wx.TextCtrl(self, -1, "0.3")
        self.label_3 = wx.StaticText(self, -1, "Número de puntos mallado", style=wx.ALIGN_CENTRE)
        self.mallado = wx.TextCtrl(self, -1, "120")
        self.label_6 = wx.StaticText(self, -1, "Longitud mojada del perfil [m]", style=wx.ALIGN_CENTRE)
        self.longi = wx.TextCtrl(self, -1, "1.02")
        self.label_9 = wx.StaticText(self, -1, "Semienvergadura [m]", style=wx.ALIGN_CENTRE)
        self.semienvergadura = wx.TextCtrl(self, -1, "6")
        self.boton = wx.Button(self, -1, "Calcular")
        self.curvas = MplPanel_1(self, -1)
        self.superficie = MplPanel_2(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onclick, self.boton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Cuadro.__set_properties
        self.SetTitle("Cálculo de la convección exterior y flujo de calor por agua impactada")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Cuadro.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(4, 6, 2, 2)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.Mmin, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.hmin, 0, 0, 0)
        grid_sizer_1.Add(self.label_7, 0, 0, 0)
        grid_sizer_1.Add(self.diam, 0, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.Mmax, 0, 0, 0)
        grid_sizer_1.Add(self.label_5, 0, 0, 0)
        grid_sizer_1.Add(self.hmax, 0, 0, 0)
        grid_sizer_1.Add(self.label_8, 0, 0, 0)
        grid_sizer_1.Add(self.altcorte, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.mallado, 0, 0, 0)
        grid_sizer_1.Add(self.label_6, 0, 0, 0)
        grid_sizer_1.Add(self.longi, 0, 0, 0)
        grid_sizer_1.Add(self.label_9, 0, 0, 0)
        grid_sizer_1.Add(self.semienvergadura, 0, 0, 0)
        grid_sizer_1.Add((10, 10), 0, 0, 0)
        grid_sizer_1.Add((10, 10), 0, 0, 0)
        grid_sizer_1.Add((10, 10), 0, 0, 0)
        grid_sizer_1.Add((10, 10), 0, 0, 0)
        grid_sizer_1.Add((10, 10), 0, 0, 0)
        grid_sizer_1.Add(self.boton, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.curvas, 1, wx.EXPAND, 0)
        sizer_2.Add(self.superficie, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onclick(self, event):  # wxGlade: Cuadro.<event_handler>
        
        Cp = 1004
        hfg = 2300
        Ka = 0.02
        Kal = 209
        R = 287
        g = 9.81
        
        
########Lectura de datos####################################
        try:
            D = float(self.diam.GetValue())
            Sw = float(self.longi.GetValue())
            mallado = float(self.mallado.GetValue())
            H = float(self.altcorte.GetValue())

            L = float(self.semienvergadura.GetValue())
            
            Mmin = float(self.Mmin.GetValue())
            Mmax = float(self.Mmax.GetValue())

            hmin = float(self.hmin.GetValue())
            hmax = float(self.hmax.GetValue())
        except:
            dlg = wx.MessageDialog(self, "Introduce valores numéricos",
                                    "Error", wx.OK)
            dlg.ShowModal()
            dlg.Destroy()
            return
#############################################################        
        
        m = linspace(Mmin,Mmax,mallado)
        h = linspace(hmin,hmax,mallado)
        
        
        mm,hh = meshgrid(m,h)
        
        
        Tinf = 288.15-0.0065*hh
		
        a = (1.4*R*Tinf)**0.5
		
        mu = 0.00001827*((291.15+120)/(Tinf+120))*(Tinf/291.15)**1.5
		
        Pr = mu*Cp/Ka
		
        rPr = Pr**0.5
		
        Ttinf = Tinf*(1+0.2*rPr*mm**2)
		
        ro = 1.225*((288.15-0.0065*hh)/288.15)**((g/(R*0.0065))-1)
		
        he = Ka*0.57*Pr**(0.4)*((4*ro*mm*(1.4*R*Tinf)**0.5)/(mu*D))**0.5
		
        LWC = 1.478750e-8*hh**2-2.418000e-04*hh+1.082250  #Revisar!!!!!
		
        Uinf = mm*a
        
        mw = LWC/1000*H*L*Uinf
		
        qw = mw/(L*Sw)*hfg
        
        #PAnel izquierdo
        self.curvas.figure.clf()
        self.curvas.axes = self.curvas.figure.add_subplot(111)
        cs = self.curvas.axes.contour(m, h, he, 25)
        self.curvas.axes.clabel(cs, inline=1, fontside=10)
        self.curvas.axes.set_title('Conveccion exterior')
        self.curvas.canvas.draw()
        
        
        #Panel derecho 
        self.superficie.figure.clf()
        ax = self.superficie.figure.add_subplot(111, projection='3d')
        ax.plot_surface(mm, hh,qw , rstride=8, cstride=8, alpha=0.3)
        cset = ax.contourf(mm, hh, qw, 20, zdir='z', offset=0)
        cset = ax.contourf(mm, hh, qw, 20, zdir='x', offset=0)
        cset = ax.contourf(mm, hh, qw, 20, zdir='y', offset=0,)


        ax.set_xlabel('Mach')
        ax.set_xlim(0, 1)
        ax.set_ylabel('Altitud')
        ax.set_ylim(0, 11000)
        ax.set_zlabel('Calor agua')
        ax.set_zlim(0, 250)

        ax.set_title('Flujo calor agua ingerida')
        
        self.superficie.canvas.draw()
        
        event.Skip()

# end of class Cuadro
