# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Apr  9 13:14:56 2014

import wx
from matplotlib.figure import Figure
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
#from numpy import *

#import matplotlib.pyplot as plt
#from matplotlib import cm
#from mpl_toolkits.mplot3d import Axes3D

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MplPanel_1(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MplPanel_1.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        ##########################
        self.figure = Figure(figsize=(6, 6), dpi=100)
        self.canvas = FigureCanvas(self, wx.ID_ANY, self.figure)
        ##########################
        
        

    def __set_properties(self):
        # begin wxGlade: MplPanel_1.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MplPanel_1.__do_layout
        pass
        # end wxGlade

# end of class MplPanel_1
